
default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: XPS15\robin
  password: Aboochi123#
  host: localhost

development:
  <<: *default
  database: BorasTestDB

production:
  <<: *default
  database: BorasTestDB
 
