
default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: SQL1\robbor
  password: Elnat2018xgre!
  host: SQL1.bornet.se

development:
  <<: *default
  database: Invoice_manager

production:
  <<: *default
  database: Invoice_manager
 
